/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ukk_spp;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class MenuUtama extends javax.swing.JFrame {
    private String level;
    public void setLevel(String a) {
        level=a;
        if(level.equals("admin")){
        }else if(level.equals("petugas")){
            mn_master.hide();
            laporan.hide();
        }else if(level.equals("siswa")){
            mn_pembayaran.hide();
            mn_master.hide();
            laporan.hide();
        }else{
            JOptionPane.showMessageDialog(null, "Level tidak ditemukan");
        }
    }

    /**
     * Creates new form MenuUtama
     */
    public MenuUtama() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mn_login = new javax.swing.JMenuItem();
        mn_master = new javax.swing.JMenu();
        mn_siswa = new javax.swing.JMenuItem();
        mn_petugas = new javax.swing.JMenuItem();
        mn_kelas = new javax.swing.JMenuItem();
        mn_spp = new javax.swing.JMenuItem();
        mn_transaksi = new javax.swing.JMenu();
        mn_pembayaran = new javax.swing.JMenuItem();
        mn_history = new javax.swing.JMenuItem();
        laporan = new javax.swing.JMenu();
        mn_laporan = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(null);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/menu (1) (1).png"))); // NOI18N
        jPanel2.add(jLabel4);
        jLabel4.setBounds(0, 0, 780, 430);

        jMenu1.setText("Login");

        mn_login.setText("Logout");
        mn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_loginActionPerformed(evt);
            }
        });
        jMenu1.add(mn_login);

        jMenuBar1.add(jMenu1);

        mn_master.setText("Master Data");

        mn_siswa.setText("Data Siswa");
        mn_siswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_siswaActionPerformed(evt);
            }
        });
        mn_master.add(mn_siswa);

        mn_petugas.setText("Data Petugas");
        mn_petugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_petugasActionPerformed(evt);
            }
        });
        mn_master.add(mn_petugas);

        mn_kelas.setText("Data Kelas");
        mn_kelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_kelasActionPerformed(evt);
            }
        });
        mn_master.add(mn_kelas);

        mn_spp.setText("Data SPP");
        mn_spp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_sppActionPerformed(evt);
            }
        });
        mn_master.add(mn_spp);

        jMenuBar1.add(mn_master);

        mn_transaksi.setText("Transaksi");

        mn_pembayaran.setText("Transaksi Pembayaran");
        mn_pembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_pembayaranActionPerformed(evt);
            }
        });
        mn_transaksi.add(mn_pembayaran);

        mn_history.setText("History Pembayaran");
        mn_history.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_historyActionPerformed(evt);
            }
        });
        mn_transaksi.add(mn_history);

        jMenuBar1.add(mn_transaksi);

        laporan.setText("Laporan");
        laporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporanActionPerformed(evt);
            }
        });

        mn_laporan.setText("Laporan Transaksi");
        mn_laporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_laporanActionPerformed(evt);
            }
        });
        laporan.add(mn_laporan);

        jMenuBar1.add(laporan);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 777, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mn_siswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_siswaActionPerformed
        // TODO add your handling code here:
        form_siswa fs=new form_siswa();
        fs.show();
        this.dispose();
    }//GEN-LAST:event_mn_siswaActionPerformed

    private void mn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_loginActionPerformed
        // TODO add your handling code here:
        login l=new login();
        l.show();
        this.dispose();
    }//GEN-LAST:event_mn_loginActionPerformed

    private void mn_petugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_petugasActionPerformed
        // TODO add your handling code here:
        form_petugas fp=new form_petugas();
        fp.show();
        this.dispose();
    }//GEN-LAST:event_mn_petugasActionPerformed

    private void mn_kelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_kelasActionPerformed
        // TODO add your handling code here:
        form_kelas fk=new form_kelas();
        fk.show();
        this.dispose();
    }//GEN-LAST:event_mn_kelasActionPerformed

    private void mn_sppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_sppActionPerformed
        // TODO add your handling code here:
        form_spp fs=new form_spp();
        fs.show();
        this.dispose();
    }//GEN-LAST:event_mn_sppActionPerformed

    private void mn_pembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_pembayaranActionPerformed
        // TODO add your handling code here:
        form_pembayaran fp=new form_pembayaran();
        fp.show();
        this.dispose();
    }//GEN-LAST:event_mn_pembayaranActionPerformed

    private void mn_historyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_historyActionPerformed
        // TODO add your handling code here:
        history_pembayaran hp=new history_pembayaran();
        hp.show();
        this.dispose();
    }//GEN-LAST:event_mn_historyActionPerformed

    private void laporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporanActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_laporanActionPerformed

    private void mn_laporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_laporanActionPerformed
        // TODO add your handling code here:
         form_laporan fl=new form_laporan();
        fl.show();
        this.dispose();
    }//GEN-LAST:event_mn_laporanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JMenu laporan;
    private javax.swing.JMenuItem mn_history;
    private javax.swing.JMenuItem mn_kelas;
    private javax.swing.JMenuItem mn_laporan;
    private javax.swing.JMenuItem mn_login;
    private javax.swing.JMenu mn_master;
    private javax.swing.JMenuItem mn_pembayaran;
    private javax.swing.JMenuItem mn_petugas;
    private javax.swing.JMenuItem mn_siswa;
    private javax.swing.JMenuItem mn_spp;
    private javax.swing.JMenu mn_transaksi;
    // End of variables declaration//GEN-END:variables
}
